### ISSUE TITLE
Unknown Locale: UTF-8

### ISSUE THREAD

**Issue by CalebGrove** [idpaterson/alfred-wunderlist-workflow#61] opened 2015-04-10 04:22 UTC
When I try to create a task, I see this error after typing `wl␣`:

![Image](http://d.pr/i/1cg3P+)

Here's the error log:
~~~~
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:12:32 workflow.py:1972 DEBUG    Workflow version : 0.4.0-beta.2
22:12:32 workflow.py:1387 DEBUG    Reading settings from `/Users/Caleb/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/settings.json` ...
22:12:32 workflow.py:2233 DEBUG    Update check not due
22:12:32 workflow.py:2350 DEBUG    Got password : com.ipaterson.alfred.wunderlist:oauth_token
22:12:32 workflow.py:1496 DEBUG    No data stored for `prefs`
22:12:32 workflow.py:1990 ERROR    unknown locale: UTF-8
Traceback (most recent call last):
  File "/Users/Caleb/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13E3F0E5-295F-4BD0-A335-58BA58C01526/workflow/workflow.py", line 1983, in run
    func(self)
  File "alfred-wunderlist-workflow.py", line 12, in main
    route(wf.args)
  File "/Users/Caleb/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13E3F0E5-295F-4BD0-A335-58BA58C01526/wunderlist/handlers/route.py", line 54, in route
    handler.filter(command)
  File "/Users/Caleb/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13E3F0E5-295F-4BD0-A335-58BA58C01526/wunderlist/handlers/tasks.py", line 17, in filter
    task = _task(args)
  File "/Users/Caleb/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13E3F0E5-295F-4BD0-A335-58BA58C01526/wunderlist/handlers/tasks.py", line 14, in _task
    return TaskParser(' '.join(args))
  File "/Users/Caleb/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13E3F0E5-295F-4BD0-A335-58BA58C01526/wunderlist/models/task_parser.py", line 60, in __init__
    self._parse()
  File "/Users/Caleb/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13E3F0E5-295F-4BD0-A335-58BA58C01526/wunderlist/models/task_parser.py", line 67, in _parse
    loc = locale.getdefaultlocale()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
22:12:32 workflow.py:2008 DEBUG    Workflow finished in 0.040 seconds.
~~~~

**Comment by idpaterson** [comment] 2015-04-10 13:41
Thanks for reporting, let's see... Can you open up the terminal and run this command for me?
```bash
python -c "import locale;print locale.getdefaultlocale()"
```

Would you also send a screenshot of the Language & Region screen from your System Preferences? Thanks!

**Comment by CalebGrove** [comment] 2015-04-10 15:34
The command returns this:

    ('en_US', 'UTF-8')

![](http://d.pr/i/14gWK+)

**Comment by idpaterson** [comment] 2015-04-10 15:59
I did a bit of research; that seems like a fairly common problem. I'm going to have to expect the possibility of an error when getting your locale and avoid crashing the workflow.

[Here is more info](http://patrick.arminio.info/fix-valueerror-unknown-locale-utf8/) on the problem and how someone solved it. I think your case is somewhat opposite; the locale is set properly in the terminal as shown by the python command but apparently not in Alfred. 

Have you customized any settings in Alfred that might be related to localization, such as the Force Keyboard option?

**Comment by CalebGrove** [comment] 2015-04-10 16:36
The "Force Keyboard" option in Alfred is blank (which is the default). To my knowledge, I've not changed any other settings that could modify my locale.

    ~> defaults read -g AppleLocale
    en_US
    
    ~> defaults read -g AppleLanguages
    (
    en
    )

**Comment by idpaterson** [comment] 2015-04-10 16:42
Thanks, I'll work on a few test builds to see which fix works best for you.

**Comment by kimonostereo** [comment] 2015-04-10 23:19
I see the same issue when I tried this workflow today.

**Comment by CalebGrove** [comment] 2015-04-10 23:21
Yeah, I know the workflow worked for me before. I wonder if this bug has anything to do with the latest OS X updates?

**Comment by kimonostereo** [comment] 2015-04-10 23:24
It might be! I updated the other day to 10.10.3... hrm...

**Comment by idpaterson** [comment] 2015-04-11 01:16
Good call, updating now...

**Comment by idpaterson** [comment] 2015-04-11 02:16
It's still working for me in 10.10.3 so that may not be the cause. Let's try a few experiments when you have time since I can't replicate the issue on my end:

1. [Test 1](https://github.com/idpaterson/alfred-wunderlist-workflow/blob/experiment/export-locale/Wunderlist.alfredworkflow?raw=true) exports your locale from AppleLocale into the environment running the workflow.
2. [Test 2](https://github.com/idpaterson/alfred-wunderlist-workflow/blob/experiment/catch-locale-exception/Wunderlist.alfredworkflow?raw=true) catches the exception, which should also fix the problem unless it crops up somewhere else in the code.

Hopefully both of these will work for you in which case the final solution will use both. Just click each to download then open the .alfredworkflow file.

**Comment by CalebGrove** [comment] 2015-04-11 02:24
Thanks! Test #1 still has the same problem, but Test #2 works as it should. :)

**Comment by idpaterson** [comment] 2015-04-11 02:30
Thanks! I think I messed up the first test build, it did not have the changes. Can you try downloading test 1 again?

**Comment by CalebGrove** [comment] 2015-04-11 02:35
I'm afraid that Test 1 is still not working for me.

**Comment by idpaterson** [comment] 2015-04-11 02:48
Two more if you don't mind:

1. [Test 3](https://github.com/idpaterson/alfred-wunderlist-workflow/blob/f1f75bbd579c6f3c188ad5e9486e8989b949687f/Wunderlist.alfredworkflow?raw=true) using LC_CTYPE instead of LANG
2. [Test 4](https://github.com/idpaterson/alfred-wunderlist-workflow/blob/18f007d487f79f0301287e08d6b9c528ccdfe926/Wunderlist.alfredworkflow?raw=true) using LC_ALL instead of LANG

**Comment by idpaterson** [comment] 2015-04-11 03:39
@kimonostereo, could you please try these four test workflows as well?

**Comment by CalebGrove** [comment] 2015-04-11 04:33
Both 3 and 4 work perfectly for me.

**Comment by kimonostereo** [comment] 2015-04-11 06:46
Thanks! Sorry, I was out for a bit.
Yay! Both of them work great!

**Comment by idpaterson** [comment] 2015-04-11 16:29
That's awesome, thanks for testing! Hopefully that won't have any adverse effects on people not facing this issue, I should probably set both the date locale and language since they may differ. Oddly, the LANG, LC_CTYPE, and LC_ALL variables do not have any value for me when running in Alfred, either but defining them does not seem to cause any harm.

@kimonostereo, I recognized your name from the Alfred forums a few years ago. While I have you here, can you test #19 where you described missing characters at the end of your tasks? It should finally fixed in 0.4 regardless of how fast you type, previously the problem was just lessened.

**Comment by kimonostereo** [comment] 2015-04-11 18:29
No problem! I haven't had any issues entering tasks and all characters seem to be there when complete. This workflow really works well!

**Comment by kimonostereo** [comment] 2015-04-11 18:49
Hmmm. Spoke too soon. Seem to be getting a JSON object could not be decoded error when I try to create a new list.

**Comment by idpaterson** [comment] 2015-04-13 12:35
@kimonostereo, the same just happened to me when creating a new task. I'll open a new issue for that with instructions for a workaround.

**Comment by idpaterson** [comment] 2015-04-14 17:08
Are you folks using pre-release Alfred builds? I noticed in the changelog for yesterday's Alfred update
> •	Add LC_CTYPE=UTF-8 encoding to script environment
> •	Add PYTHONIOENCODING=utf-8 environment variable for Python scripts

This is almost certainly what broke the workflow. Sheesh, the one time I neglect to ask for OS X and Alfred versions in a bug report :)

I'm going to have to figure out why they did that; UTF-8 is not a valid value for LC_CTYPE. Need to get a new beta out with that fix since now it's going to break for everyone!

**Comment by CalebGrove** [comment] 2015-04-14 17:10
Haha, yep, I'm on pre-release.

**Comment by kimonostereo** [comment] 2015-04-14 17:16
Oh sorry! Yes I am on the pre-release of Alfred. 

Also, previously, I was running the Wunderlist beta 3.0.3 (44), but ever since they've been having issues with the Mac beta downloads, I switched to the release version 2.2.0 (17).

**Comment by idpaterson** [comment] 2015-04-14 17:19
Thanks! I filed a [bug report](http://www.alfredforum.com/topic/5777-utf-8-is-not-a-valid-value-for-lc-ctype-flag-exception-in-python-workflows/) with Alfred.

**Comment by idpaterson** [comment] 2015-04-15 02:34
Please download 0.4.0-beta.3 for fixes to this and other issues.

**Closed by idpaterson** 2015-04-15 02:34 UTC
Labels: bug

**Comment by preppeller** [comment] 2015-04-15 08:57
Sorry about this! I've updated the bug report and reverted the LC_CTYPE change in Alfred 2.7.1 which is now available. Thanks for the input.

**Comment by idpaterson** [comment] 2015-04-15 09:54
Thanks for the quick fix!
